{{- $name := "note" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ $name }}-service
  labels:
    {{- include "brambling-note-be-java.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.note.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "brambling-note-be-java.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
